# Generated by Django 3.0.1 on 2019-12-28 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='QL_USR_DT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ql_usr_img_link', models.ImageField(upload_to='user-profile-picture')),
                ('ql_usr_name', models.CharField(max_length=60)),
                ('ql_usr_email', models.EmailField(max_length=254)),
                ('ql_usr_username', models.CharField(max_length=30)),
            ],
        ),
    ]
