# Generated by Django 3.0.1 on 2019-12-28 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='QL_FREE_DT',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ql_usr_img_link', models.ImageField(upload_to='freelance-profile-picture')),
                ('ql_free_name', models.CharField(max_length=60)),
                ('ql_free_email', models.EmailField(max_length=254)),
                ('ql_free_desc', models.TextField(max_length=500)),
            ],
        ),
    ]
