# Generated by Django 3.0.1 on 2019-12-28 21:02

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_ql_free_dt'),
    ]

    operations = [
        migrations.AddField(
            model_name='ql_usr_dt',
            name='ql_usr_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
