# Generated by Django 3.0.1 on 2019-12-28 21:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_ql_usr_dt_ql_usr_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='ql_free_dt',
            name='ql_free_created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ql_free_dt',
            name='ql_free_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
        migrations.AddField(
            model_name='ql_usr_dt',
            name='ql_usr_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1),
        ),
    ]
