# Generated by Django 3.0.1 on 2019-12-29 05:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20191228_1530'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ql_free_dt',
            old_name='ql_usr_img_link',
            new_name='ql_free_img_link',
        ),
        migrations.AddField(
            model_name='ql_free_dt',
            name='ql_free_username',
            field=models.CharField(default='', max_length=30, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ql_free_dt',
            name='ql_usr_pass',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ql_usr_dt',
            name='ql_usr_pass',
            field=models.CharField(default='', max_length=64),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='ql_free_dt',
            name='ql_free_desc',
            field=models.TextField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='ql_free_dt',
            name='ql_free_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ql_usr_dt',
            name='ql_usr_email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='ql_usr_dt',
            name='ql_usr_username',
            field=models.CharField(max_length=30, unique=True),
        ),
    ]
