# Generated by Django 3.0.1 on 2019-12-29 05:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20191228_2350'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ql_free_dt',
            old_name='ql_usr_pass',
            new_name='ql_free_pass',
        ),
    ]
