# Generated by Django 3.0.1 on 2019-12-30 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20191228_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ql_free_dt',
            name='ql_free_gender',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], default='M', max_length=1),
        ),
        migrations.AlterField(
            model_name='ql_free_dt',
            name='ql_free_pass',
            field=models.CharField(max_length=254),
        ),
        migrations.AlterField(
            model_name='ql_usr_dt',
            name='ql_usr_gender',
            field=models.CharField(choices=[('M', 'Hombre'), ('F', 'Mujer')], default='M', max_length=1),
        ),
    ]
