# Generated by Django 3.0.1 on 2019-12-30 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20191229_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ql_free_dt',
            name='ql_free_img_link',
            field=models.ImageField(default='./qtz_default/img/img_avatar.png', upload_to='freelance-profile-picture'),
        ),
    ]
