# Generated by Django 3.0.1 on 2020-01-11 20:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20191230_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ql_usr_dt',
            name='ql_usr_pass',
            field=models.CharField(max_length=254),
        ),
    ]
