# Generated by Django 3.0.2 on 2020-03-28 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20200328_1247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Freelancer_Data',
            new_name='QL_FREE_DT',
        ),
        migrations.RenameModel(
            old_name='User_Data',
            new_name='QL_USR_DT',
        ),
        migrations.AlterModelTable(
            name='ql_free_dt',
            table=None,
        ),
        migrations.AlterModelTable(
            name='ql_usr_dt',
            table=None,
        ),
    ]
