# Generated by Django 3.0.2 on 2020-03-28 21:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20200328_1453'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='QL_FREE_DT',
            new_name='Freelancer_Data',
        ),
        migrations.RenameModel(
            old_name='QL_USR_DT',
            new_name='User_Data',
        ),
        migrations.AlterModelTable(
            name='freelancer_data',
            table='Freelancer_Data',
        ),
        migrations.AlterModelTable(
            name='user_data',
            table='ql_usr_dt',
        ),
    ]
