# Generated by Django 3.0.2 on 2020-03-28 22:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20200328_1501'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='freelancer_data',
            table='ql_free_dt',
        ),
    ]
